version: "3.9"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - "80:80"
      - "443:443"

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
