version: "3.9"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    volumes:
      - ./data/wordpress:/var/www/html
    env_file: .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    volumes:
      - ./data/mariadb:/var/lib/mysql
    env_file: .env
    networks:
      - inception
    # restart: on-failure

networks:
  inception:
    name: inception
    driver: bridge
